### ISSUE TITLE
Is this including optional and driver updates?

### ISSUE THREAD

**Issue by MalteKiefer** [ceshihao/windowsupdate#1]
Hello,

does this module include driver and optional Windows updates?

**Comment by ceshihao** [comment]
> Hello,
> 
> does this module include driver and optional Windows updates?

Yes, this library is only a golang binding for Windows [Wuapi](https://docs.microsoft.com/en-us/windows/win32/wua_sdk/portal-client). You can do anything Wuapi supported. 

e.g. include driver and optional ones by [criteria settings](https://docs.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesearcher-search#remarks)

![image](https://user-images.githubusercontent.com/7711875/147320537-c0b0a3fa-d0fb-475a-a32b-f3d9d37130f8.png)
